<?php

namespace Whilesmart\Transactions\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Whilesmart\Transactions\Database\Factories\TransactionFactory;
use Whilesmart\Transactions\Enums\TransactionDirection;
use Whilesmart\Transactions\Enums\TransactionStatus;
use Whilesmart\Transactions\Enums\TransactionType;
use Whilesmart\Transactions\Events\TransactionRecorded;

class Transaction extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];

    protected $casts = [
        'type' => TransactionType::class,
        'direction' => TransactionDirection::class,
        'status' => TransactionStatus::class,
        'amount_cents' => 'integer',
        'occurred_at' => 'datetime',
        'metadata' => 'array',
    ];

    protected static function booted(): void
    {
        static::creating(function (Transaction $transaction) {
            if ($transaction->type === null) {
                $transaction->type = TransactionType::Deposit;
            }

            if ($transaction->direction === null) {
                $transaction->direction = $transaction->type->defaultDirection() ?? TransactionDirection::Credit;
            }

            if ($transaction->status === null) {
                $transaction->status = TransactionStatus::Posted;
            }

            if ($transaction->occurred_at === null) {
                $transaction->occurred_at = now();
            }

            if (empty($transaction->reference)) {
                $transaction->reference = static::generateReference($transaction);
            }
        });

        static::created(function (Transaction $transaction) {
            TransactionRecorded::dispatch($transaction);
        });
    }

    /**
     * Next per-owner transaction reference, e.g. TXN-00001. Bumps past any
     * reference already taken for this owner so the (owner, reference)
     * unique holds.
     */
    public static function generateReference(Transaction $transaction): string
    {
        $prefix = (string) config('transactions.reference_prefix', 'TXN-');
        $base = static::withTrashed()
            ->where('owner_type', $transaction->owner_type)
            ->where('owner_id', $transaction->owner_id);

        $seq = (clone $base)->count();

        do {
            $seq++;
            $reference = $prefix.str_pad((string) $seq, 5, '0', STR_PAD_LEFT);
        } while ((clone $base)->where('reference', $reference)->exists());

        return $reference;
    }

    public function getTable(): string
    {
        return config('transactions.transactions_table', 'transactions');
    }

    public function owner(): MorphTo
    {
        return $this->morphTo();
    }

    public function account(): MorphTo
    {
        return $this->morphTo();
    }

    public function counterAccount(): MorphTo
    {
        return $this->morphTo();
    }

    public function source(): MorphTo
    {
        return $this->morphTo();
    }

    public function scopePosted(Builder $query): Builder
    {
        return $query->where('status', TransactionStatus::Posted->value);
    }

    /**
     * Entries generated by a given document. Used to keep posting idempotent
     * and to find sources that have not been posted yet.
     */
    public function scopeForSource(Builder $query, Model $source): Builder
    {
        return $query->where('source_type', $source->getMorphClass())
            ->where('source_id', $source->getKey());
    }

    /**
     * The amount signed by direction: credits add to the account balance,
     * debits subtract.
     */
    public function signedAmountCents(): int
    {
        return $this->direction->sign() * (int) $this->amount_cents;
    }

    protected static function newFactory(): TransactionFactory
    {
        return TransactionFactory::new();
    }
}
